project:
  type: website
  output-dir: docs 

website:
  google-analytics: G-YPLPB5BV32
  title: "WILLIAM TILLECZEK"
  
  page-footer: 
    right: |
      Made with <a href="https://quarto.org" target="_blank">Quarto</a>\
      <span style="color: #b76e5f">Last modified: May 2025</span>
    left: |
      <span style="color: #FFFFFF">&copy; 2024 William Tilleczek</span>
    border: true
    background: "#303d4e"
    foreground: white
  
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - about.qmd
      - research.qmd
      - teaching.qmd
      - text: "CV"
        href: cv/index.qmd
      - contact.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

